# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'PHP | Include OS-specific variables.'
  include_vars: '{{ ansible_os_family }}.yml'
  tags:
    - 'php'
    - 'php-package'
    - 'php-configure'
    - 'php-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'PHP | Define OS-specific PHP version.'
  set_fact:
    php_os_version: '{{ php_version | replace(".", "") + "w" if ansible_os_family == "RedHat" else php_version }}'
  tags:
    - 'php'
    - 'php-package'
    - 'php-configure'
    - 'php-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'PHP | Define PHP packages.'
  set_fact:
    php_packages: '{{ php_default_packages }}'
  when: 'not php_packages'
  tags:
    - 'php'
    - 'php-package'
    - 'php-configure'
    - 'php-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'PHP | Define PHP PEAR package name.'
  set_fact:
    php_pear_package_name: 'php-pear'
  when: 'php_pear_package_name is not defined'
  tags:
    - 'php'
    - 'php-package'
    - 'php-configure'
    - 'php-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'PHP | Define PHP package pattern.'
  set_fact:
    php_package_pattern: '{{ php_default_package_pattern }}'
  when: 'php_package_pattern is not defined'
  tags:
    - 'php'
    - 'php-package'
    - 'php-configure'
    - 'php-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'PHP | Define PHP FPM service name.'
  set_fact:
    php_fpm_service_name: '{{ php_default_fpm_service_name }}'
  when: 'php_fpm_service_name is not defined'
  tags:
    - 'php'
    - 'php-package'
    - 'php-configure'
    - 'php-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'PHP | Define PHP FPM conf file.'
  set_fact:
    php_fpm_conf_file: '{{ php_default_fpm_conf_file }}'
  when: 'php_fpm_conf_file is not defined'
  tags:
    - 'php'
    - 'php-package'
    - 'php-configure'
    - 'php-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'PHP | Define PHP FPM pid file.'
  set_fact:
    php_fpm_pid_file: '{{ php_default_fpm_pid_file }}'
  when: 'php_fpm_pid_file is not defined'
  tags:
    - 'php'
    - 'php-package'
    - 'php-configure'
    - 'php-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'PHP | Define PHP FPM error log.'
  set_fact:
    php_fpm_error_log: '{{ php_default_fpm_error_log }}'
  when: 'php_fpm_error_log is not defined'
  tags:
    - 'php'
    - 'php-package'
    - 'php-configure'
    - 'php-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'PHP | Define PHP FPM pool path.'
  set_fact:
    php_fpm_pool_path: '{{ php_default_fpm_pool_path }}'
  when: 'php_fpm_pool_path is not defined'
  tags:
    - 'php'
    - 'php-package'
    - 'php-configure'
    - 'php-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'PHP | Define PHP ini file.'
  set_fact:
    php_ini_file: '{{ php_default_ini_file }}'
  when: 'php_ini_file is not defined'
  tags:
    - 'php'
    - 'php-package'
    - 'php-configure'
    - 'php-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'PHP | Define PHP CLI ini file.'
  set_fact:
    php_cli_ini_file: '{{ php_default_cli_ini_file }}'
  when: 'php_cli_ini_file is not defined'
  tags:
    - 'php'
    - 'php-package'
    - 'php-configure'
    - 'php-service'
    - 'package'
    - 'configure'
    - 'service'

- import_tasks: 'package.yml'
  tags:
    - 'php'
    - 'php-package'
    - 'package'

- import_tasks: 'configure.yml'
  tags:
    - 'php'
    - 'php-configure'
    - 'configure'

- import_tasks: 'service.yml'
  tags:
    - 'php'
    - 'php-service'
    - 'service'