# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'PHP | Include OS-specific variables.'
  include_vars: '{{ ansible_os_family }}.yml'
  tags:
    - 'php'
    - 'php-package'
    - 'php-configure'
    - 'php-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'PHP | Define OS-specific PHP version.'
  set_fact:
    php_os_version: '{{ php_version | replace(".", "") + "w" if ansible_os_family == "RedHat" else php_version }}'
  tags:
    - 'php'
    - 'php-package'
    - 'php-configure'
    - 'php-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'PHP | Define PHP packages.'
  set_fact:
    php_packages: '{{ php_default_packages }}'
  when: 'not php_packages'
  tags:
    - 'php'
    - 'php-package'
    - 'php-configure'
    - 'php-service'
    - 'package'
    - 'configure'
    - 'service'

- include: 'package.yml'
  tags:
    - 'php'
    - 'php-package'
    - 'package'

- include: 'configure.yml'
  tags:
    - 'php'
    - 'php-configure'
    - 'configure'

- include: 'service.yml'
  tags:
    - 'php'
    - 'php-service'
    - 'service'