# This source file is subject to the (Open Source Initiative) BSD license
# that is bundled with this package in the LICENSE file. It is also available
# through the world-wide-web at this URL: http://www.ontic.com.au/license.html
# If you did not receive a copy of the license and are unable to obtain it through
# the world-wide-web, please send an email to license@ontic.com.au immediately.
# Copyright (c) 2010-2016 Ontic. (http://www.ontic.com.au). All rights reserved.

---

- name: restart web server
  become: yes
  service:
    name: '{{ php_web_server_service_name }}'
    state: restarted
  when: php_web_server_service_name

- name: restart php-fpm
  become: yes
  service:
    name: '{{ php_fpm_service_name }}'
    state: restarted